// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { systemAdminPlugin as systemAdminPluginFactory } from "convex-zen/plugins/system-admin";
import { auth } from "../../_runtime";

const pluginGateway = systemAdminPluginFactory.definition.gateway;

type PluginRuntime = (typeof auth.plugins)["systemAdmin"];
type PluginRuntimeReturn<TFunctionName extends keyof PluginRuntime & string> =
  PluginRuntime[TFunctionName] extends (...args: never[]) => infer TReturn
    ? TReturn
    : never;

function runPluginRuntimeFunction<TFunctionName extends keyof PluginRuntime & string>(
  ctx: unknown,
  functionName: TFunctionName,
  args: Record<string, unknown>
): PluginRuntimeReturn<TFunctionName> {
  const pluginRuntime = auth.plugins["systemAdmin"];
  if (!pluginRuntime || typeof pluginRuntime !== "object") {
    throw new Error("Missing generated plugin runtime for \"systemAdmin\".");
  }
  const fn = pluginRuntime[functionName];
  if (typeof fn !== "function") {
    throw new Error(
      `Missing generated plugin runtime function for "systemAdmin.${functionName}".`
    );
  }
  return (
    fn as (
      this: PluginRuntime,
      ctx: unknown,
      args: Record<string, unknown>
    ) => PluginRuntimeReturn<TFunctionName>
  ).call(pluginRuntime, ctx, args);
}


export const banUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.banUser, "banUser"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "banUser", args);
  },
});

export const bootstrapAdmin = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.bootstrapAdmin, "bootstrapAdmin"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "bootstrapAdmin", args);
  },
});

export const canBootstrapAdmin = query({
  args: getPublicPluginFunctionArgs(pluginGateway.canBootstrapAdmin, "canBootstrapAdmin"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "canBootstrapAdmin", args);
  },
});

export const deleteUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteUser, "deleteUser"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "deleteUser", args);
  },
});

export const isAdmin = query({
  args: getPublicPluginFunctionArgs(pluginGateway.isAdmin, "isAdmin"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "isAdmin", args);
  },
});

export const listUsers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listUsers, "listUsers"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listUsers", args);
  },
});

export const setRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setRole, "setRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "setRole", args);
  },
});

export const unbanUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.unbanUser, "unbanUser"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "unbanUser", args);
  },
});
