// @generated by convex-zen generate. DO NOT EDIT.
import { defineComponent } from "convex/server";
import core from "convex-zen/core/convex.config";
import systemAdminComponent from "convex-zen-system-admin/convex.config";

const zenComponent = defineComponent("zenComponent");

zenComponent.use(core, { name: "core" });
zenComponent.use(systemAdminComponent, { name: "systemAdminComponent" });

export default zenComponent;
