// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation, query } from "./_generated/server";
import { components } from "./_generated/api";

export const signUp = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    defaultRole: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.signUp, args);
  },
});

export const signIn = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    requireEmailVerified: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.signIn, args);
  },
});

export const verifyEmail = mutation({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.verifyEmail, args);
  },
});

export const requestPasswordReset = mutation({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.requestPasswordReset, args);
  },
});

export const resetPassword = mutation({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.resetPassword, args);
  },
});

export const validateSession = mutation({
  args: {
    token: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.validateSession, args);
  },
});

export const getCurrentUser = query({
  args: {
    token: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runQuery(components.core.gateway.getCurrentUser, args);
  },
});

export const getUserById = query({
  args: {
    userId: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runQuery(components.core.gateway.getUserById, args);
  },
});

export const invalidateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.invalidateSession, args);
  },
});

export const invalidateAllSessions = mutation({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.invalidateAllSessions, args);
  },
});
