// @generated by convex-zen generate. DO NOT EDIT.
import { defineSchema } from "convex/server";
import { createCoreSchemaTables } from "convex-zen/component/core-schema-definition";
import { systemAdminPlugin as systemAdminPluginFactory } from "convex-zen/plugins/system-admin";

export default defineSchema({
  ...createCoreSchemaTables(),
  ...(systemAdminPluginFactory.definition.schema?.tables ?? {}),
});
