/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as CmsRouteRouteImport } from './routes/cms/route'
import { Route as DefaultRouteRouteImport } from './routes/_default/route'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as DefaultIndexRouteImport } from './routes/_default/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRouteRoute = CmsRouteRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultRouteRoute = DefaultRouteRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRouteRoute,
} as any)
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute
  '/cms': typeof CmsRouteRouteWithChildren
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/cms/': typeof CmsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/': typeof DefaultIndexRoute
  '/cms': typeof CmsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_default': typeof DefaultRouteRouteWithChildren
  '/cms': typeof CmsRouteRouteWithChildren
  '/reset': typeof ResetRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/_default/': typeof DefaultIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/reset'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/cms/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/'
    | '/cms'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_default'
    | '/cms'
    | '/reset'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/_default/'
    | '/cms/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  CmsRouteRoute: typeof CmsRouteRouteWithChildren
  ResetRoute: typeof ResetRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRouteRoute
    }
    '/_default/': {
      id: '/_default/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultIndexRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DefaultRouteRouteChildren {
  DefaultIndexRoute: typeof DefaultIndexRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultIndexRoute: DefaultIndexRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

interface CmsRouteRouteChildren {
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteRouteChildren: CmsRouteRouteChildren = {
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteRouteWithChildren = CmsRouteRoute._addFileChildren(
  CmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  CmsRouteRoute: CmsRouteRouteWithChildren,
  ResetRoute: ResetRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
